### ISSUE TITLE
parsererror on login with Bugzilla 4.4.1

### ISSUE THREAD

**Issue by gepandz** [EvanOman/KanbanBoard#8]
Error message is: "There was an error: parsererror" when I enter my information and click Login. I've checked, and my xmlrpc.cgi script works from the command-line -- I get results, at least.

Login entered (don't know if the + syntax in the email address is causing problems...):

![image](https://f.cloud.github.com/assets/1490432/1651027/08da4378-5abd-11e3-9af1-8931c0e7a7fc.png)

Error message (there's not a lot to go on):

![image](https://f.cloud.github.com/assets/1490432/1651007/f33558c4-5abb-11e3-91b8-eb0cefdd4e56.png)

Any tips on where to start debugging? My PHP is kinda rusty... Haven't really touched it in over 7 years.

This tool looks really neat, so I'm kinda bummed that I'm getting kicked out at the start. Thanks for writing this!

**Comment by magwas** [comment]
same problem here, no + syntax in my email. Bugzilla version is 4.4.3

**Comment by magwas** [comment]
according to logs, kanban board does not even call bugzilla...

**Comment by magwas** [comment]
the representation of the errorThrown variable is: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**Comment by kingmaiku** [comment]
I was able to fix this by removing the dataType: 'json' from loginpage.php line 106
This data doesn't seem to be in json format yet so it barfs when you tell it to expect json.

**Comment by magwas** [comment]
Cannot confirm this. ajax_login.php actually returns json.
For me the solution was to install php5-curl.
loginpage.php was not able to parse the "sorry there is no curl installed" response from ajax_login.php.

**Comment by gizzmojr** [comment]
installing php5-curl fixed my problem, thanks magwas
bugzilla: 4.4.6
Ubuntu Server 14.04.3

**Comment by EvanOman** [comment]
Can confirm that installing php5-curl will get you through the login page. I mentioned that php5-curl must be installed in the README and I will open an issue to make the login page properly parse the "sorry there is no curl installed" message. 

Thanks guys
